using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Abc.OnlineBL.Entities.Enums
{
	/// <summary>
	/// JobType enum
	/// </summary>
	public enum AOP_JobType
	{
		/// <summary>
		/// JpegPreview
		/// </summary>
		JpegPreview = 0,
		/// <summary>
		/// SaveAsIndesign
		/// </summary>
		SaveAsIndesign = 1,
		/// <summary>
		/// JpegPreview then SaveAsIndesign
		/// </summary>
		JpegPreviewAndSave = 2,
		/// <summary>
		/// Exactly like SaveAsIndesign, but save to diff location.
		/// </summary>
		/// <remarks>
		/// Because we dont want nobody to touch the .indd file untill the client approves the job
		/// or cancels the job, that's why we save the job in the CompletedJobs folder under DocumentsRoot
		/// forder. When client approves/cancels the job from CMyAbc we need to move the file from CompletedJobs
		/// to a Layout folder. But for cancelation we insert a queue in AOP database so it will generate a fresh
		/// .indd file. The problem is we are trying to move the file when it is being generated by AOP.
		/// So the enum will flag AOP to generate the file in the target folder, Layout folder, instead of CompletedJobs.
		/// </remarks>
		SaveAsIndesignToAltFolder = 3
	}
}
