//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Abc.OnlineBL.VirtualFileSystem.RemoteProxyWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FileServiceSoap", Namespace="http://tempuri.org/")]
    public partial class FileService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CopyOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadAllTextOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadAllBytesOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteAllTextOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteAllBytesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExistsDirOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDirOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteDirOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFilesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FileService() {
            this.Url = "http://localhost/Abc.OnlineBL.VirtualFileSystemProvider/FileService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExistsCompletedEventHandler ExistsCompleted;
        
        /// <remarks/>
        public event CopyCompletedEventHandler CopyCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event ReadAllTextCompletedEventHandler ReadAllTextCompleted;
        
        /// <remarks/>
        public event ReadAllBytesCompletedEventHandler ReadAllBytesCompleted;
        
        /// <remarks/>
        public event WriteAllTextCompletedEventHandler WriteAllTextCompleted;
        
        /// <remarks/>
        public event WriteAllBytesCompletedEventHandler WriteAllBytesCompleted;
        
        /// <remarks/>
        public event ExistsDirCompletedEventHandler ExistsDirCompleted;
        
        /// <remarks/>
        public event CreateDirCompletedEventHandler CreateDirCompleted;
        
        /// <remarks/>
        public event DeleteDirCompletedEventHandler DeleteDirCompleted;
        
        /// <remarks/>
        public event GetFilesCompletedEventHandler GetFilesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Exists", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Exists(string filePath) {
            object[] results = this.Invoke("Exists", new object[] {
                        filePath});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ExistsAsync(string filePath) {
            this.ExistsAsync(filePath, null);
        }
        
        /// <remarks/>
        public void ExistsAsync(string filePath, object userState) {
            if ((this.ExistsOperationCompleted == null)) {
                this.ExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExistsOperationCompleted);
            }
            this.InvokeAsync("Exists", new object[] {
                        filePath}, this.ExistsOperationCompleted, userState);
        }
        
        private void OnExistsOperationCompleted(object arg) {
            if ((this.ExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExistsCompleted(this, new ExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Copy", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Copy(string srcPath, string destPath, bool overwrite) {
            this.Invoke("Copy", new object[] {
                        srcPath,
                        destPath,
                        overwrite});
        }
        
        /// <remarks/>
        public void CopyAsync(string srcPath, string destPath, bool overwrite) {
            this.CopyAsync(srcPath, destPath, overwrite, null);
        }
        
        /// <remarks/>
        public void CopyAsync(string srcPath, string destPath, bool overwrite, object userState) {
            if ((this.CopyOperationCompleted == null)) {
                this.CopyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCopyOperationCompleted);
            }
            this.InvokeAsync("Copy", new object[] {
                        srcPath,
                        destPath,
                        overwrite}, this.CopyOperationCompleted, userState);
        }
        
        private void OnCopyOperationCompleted(object arg) {
            if ((this.CopyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CopyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Delete(string filePath) {
            this.Invoke("Delete", new object[] {
                        filePath});
        }
        
        /// <remarks/>
        public void DeleteAsync(string filePath) {
            this.DeleteAsync(filePath, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string filePath, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        filePath}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReadAllText", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReadAllText(string filePath) {
            object[] results = this.Invoke("ReadAllText", new object[] {
                        filePath});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAllTextAsync(string filePath) {
            this.ReadAllTextAsync(filePath, null);
        }
        
        /// <remarks/>
        public void ReadAllTextAsync(string filePath, object userState) {
            if ((this.ReadAllTextOperationCompleted == null)) {
                this.ReadAllTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadAllTextOperationCompleted);
            }
            this.InvokeAsync("ReadAllText", new object[] {
                        filePath}, this.ReadAllTextOperationCompleted, userState);
        }
        
        private void OnReadAllTextOperationCompleted(object arg) {
            if ((this.ReadAllTextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadAllTextCompleted(this, new ReadAllTextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReadAllBytes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ReadAllBytes(string filePath) {
            object[] results = this.Invoke("ReadAllBytes", new object[] {
                        filePath});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadAllBytesAsync(string filePath) {
            this.ReadAllBytesAsync(filePath, null);
        }
        
        /// <remarks/>
        public void ReadAllBytesAsync(string filePath, object userState) {
            if ((this.ReadAllBytesOperationCompleted == null)) {
                this.ReadAllBytesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadAllBytesOperationCompleted);
            }
            this.InvokeAsync("ReadAllBytes", new object[] {
                        filePath}, this.ReadAllBytesOperationCompleted, userState);
        }
        
        private void OnReadAllBytesOperationCompleted(object arg) {
            if ((this.ReadAllBytesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadAllBytesCompleted(this, new ReadAllBytesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WriteAllText", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WriteAllText(string filePath, string data) {
            this.Invoke("WriteAllText", new object[] {
                        filePath,
                        data});
        }
        
        /// <remarks/>
        public void WriteAllTextAsync(string filePath, string data) {
            this.WriteAllTextAsync(filePath, data, null);
        }
        
        /// <remarks/>
        public void WriteAllTextAsync(string filePath, string data, object userState) {
            if ((this.WriteAllTextOperationCompleted == null)) {
                this.WriteAllTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteAllTextOperationCompleted);
            }
            this.InvokeAsync("WriteAllText", new object[] {
                        filePath,
                        data}, this.WriteAllTextOperationCompleted, userState);
        }
        
        private void OnWriteAllTextOperationCompleted(object arg) {
            if ((this.WriteAllTextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteAllTextCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WriteAllBytes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WriteAllBytes(string filePath, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] data) {
            this.Invoke("WriteAllBytes", new object[] {
                        filePath,
                        data});
        }
        
        /// <remarks/>
        public void WriteAllBytesAsync(string filePath, byte[] data) {
            this.WriteAllBytesAsync(filePath, data, null);
        }
        
        /// <remarks/>
        public void WriteAllBytesAsync(string filePath, byte[] data, object userState) {
            if ((this.WriteAllBytesOperationCompleted == null)) {
                this.WriteAllBytesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteAllBytesOperationCompleted);
            }
            this.InvokeAsync("WriteAllBytes", new object[] {
                        filePath,
                        data}, this.WriteAllBytesOperationCompleted, userState);
        }
        
        private void OnWriteAllBytesOperationCompleted(object arg) {
            if ((this.WriteAllBytesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteAllBytesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExistsDir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ExistsDir(string dirPath) {
            object[] results = this.Invoke("ExistsDir", new object[] {
                        dirPath});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ExistsDirAsync(string dirPath) {
            this.ExistsDirAsync(dirPath, null);
        }
        
        /// <remarks/>
        public void ExistsDirAsync(string dirPath, object userState) {
            if ((this.ExistsDirOperationCompleted == null)) {
                this.ExistsDirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExistsDirOperationCompleted);
            }
            this.InvokeAsync("ExistsDir", new object[] {
                        dirPath}, this.ExistsDirOperationCompleted, userState);
        }
        
        private void OnExistsDirOperationCompleted(object arg) {
            if ((this.ExistsDirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExistsDirCompleted(this, new ExistsDirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateDir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateDir(string dirPath) {
            this.Invoke("CreateDir", new object[] {
                        dirPath});
        }
        
        /// <remarks/>
        public void CreateDirAsync(string dirPath) {
            this.CreateDirAsync(dirPath, null);
        }
        
        /// <remarks/>
        public void CreateDirAsync(string dirPath, object userState) {
            if ((this.CreateDirOperationCompleted == null)) {
                this.CreateDirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDirOperationCompleted);
            }
            this.InvokeAsync("CreateDir", new object[] {
                        dirPath}, this.CreateDirOperationCompleted, userState);
        }
        
        private void OnCreateDirOperationCompleted(object arg) {
            if ((this.CreateDirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDirCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteDir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteDir(string dirPath, bool recursive) {
            this.Invoke("DeleteDir", new object[] {
                        dirPath,
                        recursive});
        }
        
        /// <remarks/>
        public void DeleteDirAsync(string dirPath, bool recursive) {
            this.DeleteDirAsync(dirPath, recursive, null);
        }
        
        /// <remarks/>
        public void DeleteDirAsync(string dirPath, bool recursive, object userState) {
            if ((this.DeleteDirOperationCompleted == null)) {
                this.DeleteDirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDirOperationCompleted);
            }
            this.InvokeAsync("DeleteDir", new object[] {
                        dirPath,
                        recursive}, this.DeleteDirOperationCompleted, userState);
        }
        
        private void OnDeleteDirOperationCompleted(object arg) {
            if ((this.DeleteDirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteDirCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetFiles(string path, string filter) {
            object[] results = this.Invoke("GetFiles", new object[] {
                        path,
                        filter});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFilesAsync(string path, string filter) {
            this.GetFilesAsync(path, filter, null);
        }
        
        /// <remarks/>
        public void GetFilesAsync(string path, string filter, object userState) {
            if ((this.GetFilesOperationCompleted == null)) {
                this.GetFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFilesOperationCompleted);
            }
            this.InvokeAsync("GetFiles", new object[] {
                        path,
                        filter}, this.GetFilesOperationCompleted, userState);
        }
        
        private void OnGetFilesOperationCompleted(object arg) {
            if ((this.GetFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFilesCompleted(this, new GetFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ExistsCompletedEventHandler(object sender, ExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CopyCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeleteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ReadAllTextCompletedEventHandler(object sender, ReadAllTextCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadAllTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadAllTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ReadAllBytesCompletedEventHandler(object sender, ReadAllBytesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadAllBytesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadAllBytesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WriteAllTextCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void WriteAllBytesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ExistsDirCompletedEventHandler(object sender, ExistsDirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExistsDirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExistsDirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateDirCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeleteDirCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetFilesCompletedEventHandler(object sender, GetFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591