#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Reflection;
using System.Runtime.Serialization;

/* Enum of Tables Only */
namespace Abc.OnlineBL.Entities
{	
	public enum EntityRelations
	{
		#region ABCFP_FeedsConverter		
		ABCFP_FeedsConverter_To_ABCFP_IncomingAgentsInfos,
		ABCFP_FeedsConverter_To_ABCFP_OutgoingFeedsConsumer,
		ABCFP_FeedsConverter_To_ABCFP_OutgoingFeedsMappings,
		#endregion
		
		#region WorkflowType		
		WorkflowType_To_PackageContents,
		WorkflowType_To_Products,
		#endregion
		
		#region ABCFP_InboundQueue		
		ABCFP_InboundQueue_To_ABCFP_IncomingAgentsInfo,
		ABCFP_InboundQueue_To_Client,
		#endregion
		
		#region ABCFP_IncomingAgentsInfo		
		ABCFP_IncomingAgentsInfo_To_ABCFP_InboundQueues,
		ABCFP_IncomingAgentsInfo_To_ABCFP_FeedsConverter,
		#endregion
		
		#region ABCFP_IncomingFeedsMapping		
		ABCFP_IncomingFeedsMapping_To_AR_Listing,
		ABCFP_IncomingFeedsMapping_To_Client,
		#endregion
		
		#region ABCFP_IncomingImageInfo		
		ABCFP_IncomingImageInfo_To_AR_ImageDetail,
		#endregion
		
		#region ABCFP_OutboundQueue		
		ABCFP_OutboundQueue_To_ABCFP_OutgoingFeedsConsumer,
		#endregion
		
		#region ABCFP_OutgoingAgentsInfo		
		ABCFP_OutgoingAgentsInfo_To_ABCFP_OutgoingFeedsConsumer,
		ABCFP_OutgoingAgentsInfo_To_Client,
		#endregion
		
		#region ABCFP_OutgoingBlackList		
		ABCFP_OutgoingBlackList_To_ABCFP_OutgoingFeedsConsumer,
		ABCFP_OutgoingBlackList_To_AR_Listing,
		#endregion
		
		#region ABCFP_OutgoingFeedsConsumer		
		ABCFP_OutgoingFeedsConsumer_To_ABCFP_OutboundQueues,
		ABCFP_OutgoingFeedsConsumer_To_ABCFP_OutgoingAgentsInfos,
		ABCFP_OutgoingFeedsConsumer_To_ABCFP_OutgoingBlackLists,
		ABCFP_OutgoingFeedsConsumer_To_ABCFP_FeedsConverter,
		#endregion
		
		#region ABCFP_OutgoingFeedsMapping		
		ABCFP_OutgoingFeedsMapping_To_ABCFP_FeedsConverter,
		ABCFP_OutgoingFeedsMapping_To_AR_Listing,
		#endregion
		
		#region AccountCredit		
		AccountCredit_To_Payments,
		AccountCredit_To_Account,
		#endregion
		
		#region AOP_AnalyzeQueue		
		AOP_AnalyzeQueue_To_AOP_Template,
		AOP_AnalyzeQueue_To_AOP_QueueStatus,
		#endregion
		
		#region AOP_DocumentPolicy		
		AOP_DocumentPolicy_To_AOP_TemplateProducts,
		#endregion
		
		#region AOP_DocumentStatus		
		AOP_DocumentStatus_To_AOP_JobDocuments,
		#endregion
		
		#region AOP_TemplateProduct		
		AOP_TemplateProduct_To_AOP_JobDocuments,
		AOP_TemplateProduct_To_Design_Documents,
		AOP_TemplateProduct_To_AOP_DocumentPolicy,
		AOP_TemplateProduct_To_AOP_Template,
		#endregion
		
		#region AR_Agreement		
		AR_Agreement_To_Client,
		#endregion
		
		#region AR_Alert		
		AR_Alert_To_AR_User,
		#endregion
		
		#region AR_Area		
		AR_Area_To_AR_Listing,
		#endregion
		
		#region AR_BlockedClient		
		AR_BlockedClient_To_Client,
		#endregion
		
		#region AR_Document		
		AR_Document_To_AR_Listing,
		#endregion
		
		#region AR_EmailQuery		
		AR_EmailQuery_To_AR_Listing,
		#endregion
		
		#region AR_Floorplan		
		AR_Floorplan_To_AR_FloorplanIcons,
		AR_Floorplan_To_AR_Image,
		#endregion
		
		#region AR_FloorplanIcon		
		AR_FloorplanIcon_To_AR_Floorplan,
		#endregion
		
		#region AR_ForRent		
		AR_ForRent_To_AR_Listing,
		#endregion
		
		#region AR_ForSale		
		AR_ForSale_To_AR_Listing,
		#endregion
		
		#region AR_Image		
		AR_Image_To_AR_Floorplans,
		AR_Image_To_AR_ImageDetails,
		AR_Image_To_AR_Property,
		#endregion
		
		#region AR_ImageDetail		
		AR_ImageDetail_To_ABCFP_IncomingImageInfo,
		AR_ImageDetail_To_AR_Image,
		#endregion
		
		#region AR_InspectionDate		
		AR_InspectionDate_To_AR_Listing,
		#endregion
		
		#region AR_Lease		
		AR_Lease_To_AR_Listing,
		#endregion
		
		#region AR_Listing		
		AR_Listing_To_ABCFP_IncomingFeedsMapping,
		AR_Listing_To_ABCFP_OutgoingBlackLists,
		AR_Listing_To_ABCFP_OutgoingFeedsMappings,
		AR_Listing_To_AR_Areas,
		AR_Listing_To_AR_Documents,
		AR_Listing_To_AR_EmailQueries,
		AR_Listing_To_AR_ForRent,
		AR_Listing_To_AR_ForSale,
		AR_Listing_To_AR_InspectionDates,
		AR_Listing_To_AR_Lease,
		AR_Listing_To_AR_Stat,
		AR_Listing_To_AR_VisitorShortLists,
		AR_Listing_To_PropertyListings,
		AR_Listing_To_WebSitePropertyAreas,
		AR_Listing_To_WebSiteSingleProperty,
		AR_Listing_To_ABCVIS_Listings,
		AR_Listing_To_AR_Property,
		AR_Listing_To_AR_ListingType,
		AR_Listing_To_AR_Status,
		AR_Listing_To_Location,
		AR_Listing_To_Client,
		#endregion
		
		#region AR_ListingType		
		AR_ListingType_To_AR_Listings,
		#endregion
		
		#region AR_PluginClient		
		AR_PluginClient_To_AR_PluginGroupClients,
		AR_PluginClient_To_AR_Theme,
		AR_PluginClient_To_Client,
		#endregion
		
		#region AR_PluginGroupClient		
		AR_PluginGroupClient_To_AR_PluginClient,
		AR_PluginGroupClient_To_Client,
		#endregion
		
		#region AR_Stat		
		AR_Stat_To_AR_StatsDailies,
		AR_Stat_To_AR_StatsMonthlies,
		AR_Stat_To_AR_Listing,
		#endregion
		
		#region AR_StatsDaily		
		AR_StatsDaily_To_AR_Stat,
		#endregion
		
		#region AR_StatsMonthly		
		AR_StatsMonthly_To_AR_Stat,
		#endregion
		
		#region AR_Status		
		AR_Status_To_AR_Listings,
		#endregion
		
		#region AR_Theme		
		AR_Theme_To_AR_PluginClients,
		AR_Theme_To_AR_ThemeDetails,
		#endregion
		
		#region AR_ThemeDetail		
		AR_ThemeDetail_To_AR_Theme,
		AR_ThemeDetail_To_AR_ThemeMaster,
		#endregion
		
		#region AR_ThemeMaster		
		AR_ThemeMaster_To_AR_ThemeDetails,
		#endregion
		
		#region AR_User		
		AR_User_To_AR_Alerts,
		#endregion
		
		#region AR_Visitor		
		AR_Visitor_To_AR_VisitorSearchHistories,
		AR_Visitor_To_AR_VisitorShortLists,
		#endregion
		
		#region AR_VisitorSearchHistory		
		AR_VisitorSearchHistory_To_AR_Visitor,
		#endregion
		
		#region AR_VisitorShortList		
		AR_VisitorShortList_To_AR_Listing,
		AR_VisitorShortList_To_AR_Visitor,
		#endregion
		
		#region Artist		
		Artist_To_ProofDetails,
		Artist_To_TemplateChangeRequests,
		Artist_To_TemplateDetails,
		Artist_To_TemplateRequests,
		#endregion
		
		#region BusinessRegion		
		BusinessRegion_To_CRM_Clients,
		BusinessRegion_To_Photographers,
		BusinessRegion_To_Clients,
		BusinessRegion_To_State1,
		#endregion
		
		#region ClientGroup		
		ClientGroup_To_AOP_Templates,
		ClientGroup_To_UserLogons,
		ClientGroup_To_Clients,
		ClientGroup_To_TemplateDetails,
		#endregion
		
		#region ClientsDisplayInfo		
		ClientsDisplayInfo_To_Client,
		#endregion
		
		#region ClientsForAllManager		
		ClientsForAllManager_To_Client,
		#endregion
		
		#region ClientsLocation		
		ClientsLocation_To_Location,
		ClientsLocation_To_Client,
		#endregion
		
		#region ClientsOOProfile		
		ClientsOOProfile_To_OOProfile,
		ClientsOOProfile_To_Client,
		#endregion
		
		#region ClientsPref		
		ClientsPref_To_Preference,
		ClientsPref_To_Client,
		#endregion
		
		#region ClientsTheme		
		ClientsTheme_To_OOProfiles,
		#endregion
		
		#region CommOrder		
		CommOrder_To_Customer,
		CommOrder_To_Order,
		#endregion
		
		#region Consignment		
		Consignment_To_DespatchOtherDetails,
		Consignment_To_DespatchDetails,
		Consignment_To_Manager,
		#endregion
		
		#region Credit		
		Credit_To_Invoice,
		#endregion
		
		#region CRM_Activity		
		CRM_Activity_To_CRM_ActivityDetails,
		CRM_Activity_To_CRM_ActivityStatus,
		CRM_Activity_To_CRM_Department,
		CRM_Activity_To_CRM_MappedClient,
		#endregion
		
		#region CRM_ActivityDetail		
		CRM_ActivityDetail_To_CRM_Activity,
		CRM_ActivityDetail_To_CRM_ActivityDetailsStatus,
		CRM_ActivityDetail_To_CRM_ActivityDetailsType,
		CRM_ActivityDetail_To_CRM_Contact,
		#endregion
		
		#region CRM_ActivityDetailsStatus		
		CRM_ActivityDetailsStatus_To_CRM_ActivityDetails,
		#endregion
		
		#region CRM_ActivityDetailsType		
		CRM_ActivityDetailsType_To_CRM_ActivityDetails,
		#endregion
		
		#region CRM_ActivityStatus		
		CRM_ActivityStatus_To_CRM_Activities,
		#endregion
		
		#region CRM_Client		
		CRM_Client_To_CRM_MappedClients,
		CRM_Client_To_BusinessRegion,
		#endregion
		
		#region CRM_Contact		
		CRM_Contact_To_CRM_ActivityDetails,
		CRM_Contact_To_CRM_ContactType,
		CRM_Contact_To_CRM_MappedClient,
		#endregion
		
		#region CRM_ContactType		
		CRM_ContactType_To_CRM_Contacts,
		#endregion
		
		#region CRM_Department		
		CRM_Department_To_CRM_Activities,
		#endregion
		
		#region CRM_MappedClient		
		CRM_MappedClient_To_CRM_Activities,
		CRM_MappedClient_To_CRM_Contacts,
		CRM_MappedClient_To_CRM_Client,
		CRM_MappedClient_To_Client,
		#endregion
		
		#region Customer		
		Customer_To_CommOrders,
		Customer_To_Hosting_HostingConfigurations,
		Customer_To_State1,
		#endregion
		
		#region DeliveryDetail		
		DeliveryDetail_To_Order,
		DeliveryDetail_To_Photographer,
		#endregion
		
		#region Event		
		Event_To_EventSubscriptions,
		#endregion
		
		#region EventQueue		
		EventQueue_To_EventSubscription,
		#endregion
		
		#region EventSubscriber		
		EventSubscriber_To_EventSubscriptions,
		#endregion
		
		#region EventSubscription		
		EventSubscription_To_EventQueues,
		EventSubscription_To_Event,
		EventSubscription_To_EventSubscriber,
		#endregion
		
		#region Floorplan		
		Floorplan_To_FloorplanIcons,
		Floorplan_To_FloorplanPackage,
		#endregion
		
		#region FloorplanIcon		
		FloorplanIcon_To_Floorplan,
		#endregion
		
		#region FloorplanImageStore		
		FloorplanImageStore_To_FloorplanPackage,
		#endregion
		
		#region FloorplanPackage		
		FloorplanPackage_To_Floorplans,
		FloorplanPackage_To_FloorplanImageStores,
		FloorplanPackage_To_Location,
		FloorplanPackage_To_Client,
		#endregion
		
		#region Hosting_HostingConfiguration		
		Hosting_HostingConfiguration_To_Customer,
		Hosting_HostingConfiguration_To_Hosting_LinkType,
		Hosting_HostingConfiguration_To_Client,
		#endregion
		
		#region Hosting_LinkType		
		Hosting_LinkType_To_Hosting_HostingConfigurations,
		#endregion
		
		#region HostingOrderDetail		
		HostingOrderDetail_To_OrderDetail,
		#endregion
		
		#region Invoice		
		Invoice_To_Credits,
		Invoice_To_OnlinePaymentDetails,
		Invoice_To_PaymentDetails,
		Invoice_To_Order,
		#endregion
		
		#region Location		
		Location_To_AR_Listings,
		Location_To_ClientsLocations,
		Location_To_FloorplanPackages,
		Location_To_LocationsData,
		Location_To_Orders,
		Location_To_Properties,
		Location_To_OrderOtherDetails,
		Location_To_State1,
		Location_To_DriverRegions,
		#endregion
		
		#region LocationsData		
		LocationsData_To_LocationsSurrounds,
		LocationsData_To_Location,
		LocationsData_To_SubRegion,
		#endregion
		
		#region LocationsSurround		
		LocationsSurround_To_LocationsData,
		#endregion
		
		#region Manager		
		Manager_To_Consignments,
		Manager_To_ProductManagerExclusives,
		Manager_To_RunSheets,
		Manager_To_SB_Inventories,
		Manager_To_Trucks,
		Manager_To_Clients,
		Manager_To_SB_Orders,
		Manager_To_State1,
		#endregion
		
		#region MaterialDetail		
		MaterialDetail_To_Order,
		#endregion
		
		#region ODPackageContent		
		ODPackageContent_To_WorkflowAlerts,
		ODPackageContent_To_WorkflowHistories,
		ODPackageContent_To_OrderDetail,
		ODPackageContent_To_PackageContent,
		ODPackageContent_To_AJPS_Rule,
		#endregion
		
		#region OnlinePaymentDetail		
		OnlinePaymentDetail_To_Invoice,
		OnlinePaymentDetail_To_OnlinePayment,
		#endregion
		
		#region OnlinePayment		
		OnlinePayment_To_OnlinePaymentDetails,
		#endregion
		
		#region OOProfile		
		OOProfile_To_ClientsOOProfiles,
		OOProfile_To_ClientsTheme,
		#endregion
		
		#region OrderDetail		
		OrderDetail_To_HostingOrderDetail,
		OrderDetail_To_ODPackageContents,
		OrderDetail_To_WorkflowAlerts,
		OrderDetail_To_WorkflowHistories,
		OrderDetail_To_AOP_JobDocuments,
		OrderDetail_To_Order,
		OrderDetail_To_PrintTemplate,
		OrderDetail_To_Product,
		OrderDetail_To_AJPS_Rule,
		#endregion
		
		#region Order		
		Order_To_CommOrder,
		Order_To_DeliveryDetail,
		Order_To_Invoice,
		Order_To_MaterialDetail,
		Order_To_OrderDetails,
		Order_To_ProofDetail,
		Order_To_PropertyOrder,
		Order_To_WorkflowAlerts,
		Order_To_WorkflowHistories,
		Order_To_AOP_JobDocuments,
		Order_To_DroneAuthorisations,
		Order_To_TemplateChangeRequests,
		Order_To_FloorPlanOrders,
		Order_To_DespatchOtherDetails,
		Order_To_OrderOtherInfo,
		Order_To_PhotoOrderDetail,
		Order_To_DespatchDetail,
		Order_To_BoardApproval,
		Order_To_PhotoOrder,
		Order_To_Design_Documents,
		Order_To_OrderOtherDetail,
		Order_To_Location,
		Order_To_Client,
		Order_To_Account,
		#endregion
		
		#region PackageContent		
		PackageContent_To_ODPackageContents,
		PackageContent_To_WorkflowType,
		PackageContent_To_Package,
		PackageContent_To_AJPS_Rule,
		#endregion
		
		#region PackageRule		
		PackageRule_To_Package,
		#endregion
		
		#region Package		
		Package_To_PackageContents,
		Package_To_PackageRules,
		Package_To_Product,
		#endregion
		
		#region PaymentDetail		
		PaymentDetail_To_Invoice,
		PaymentDetail_To_Payment,
		#endregion
		
		#region Payment		
		Payment_To_PaymentDetails,
		Payment_To_AccountCredit,
		Payment_To_Account,
		#endregion
		
		#region Photographer		
		Photographer_To_DeliveryDetails,
		Photographer_To_PhotographerSecurities,
		Photographer_To_PhotographerSecurities1,
		Photographer_To_PhotographersGalleries,
		Photographer_To_PhotographersProfile,
		Photographer_To_PhotoNotes,
		Photographer_To_DroneAuthorisations,
		Photographer_To_DroneAuthorisations1,
		Photographer_To_DroneAuthorisations2,
		Photographer_To_PhotoOrders,
		Photographer_To_BusinessRegion,
		Photographer_To_State1,
		#endregion
		
		#region PhotographerSecurity		
		PhotographerSecurity_To_Photographer,
		PhotographerSecurity_To_Photographer1,
		#endregion
		
		#region PhotographersGallery		
		PhotographersGallery_To_Photographer,
		#endregion
		
		#region PhotographersProfile		
		PhotographersProfile_To_Photographer,
		#endregion
		
		#region PhotographersPublicGallery		
		PhotographersPublicGallery_To_PhotographersPublicGalleryCategory,
		#endregion
		
		#region PhotographersPublicGalleryCategory		
		PhotographersPublicGalleryCategory_To_PhotographersPublicGalleries,
		#endregion
		
		#region PhotoNote		
		PhotoNote_To_Photographer,
		#endregion
		
		#region Preference		
		Preference_To_ClientsPrefs,
		#endregion
		
		#region PricingType		
		PricingType_To_ProductPricings,
		#endregion
		
		#region PrintTemplate		
		PrintTemplate_To_OrderDetails,
		PrintTemplate_To_Clients,
		PrintTemplate_To_PriceListDetails,
		#endregion
		
		#region ProductManagerExclusive		
		ProductManagerExclusive_To_Manager,
		ProductManagerExclusive_To_Product,
		#endregion
		
		#region ProductPricing		
		ProductPricing_To_PricingType,
		ProductPricing_To_Product,
		#endregion
		
		#region ProductSizeCode		
		ProductSizeCode_To_ProductSizeCodeDetails,
		ProductSizeCode_To_Products,
		ProductSizeCode_To_PDF_Templates,
		ProductSizeCode_To_PrintReadyTemplates,
		#endregion
		
		#region ProductSizeCodeDetail		
		ProductSizeCodeDetail_To_ProductSizeCode,
		ProductSizeCodeDetail_To_ProductType,
		#endregion
		
		#region ProductType		
		ProductType_To_ProductSizeCodeDetails,
		ProductType_To_Products,
		#endregion
		
		#region ProofDetail		
		ProofDetail_To_Proofs,
		ProofDetail_To_Artist,
		ProofDetail_To_Order,
		#endregion
		
		#region Proof		
		Proof_To_ProofDetail,
		#endregion
		
		#region PropertyListing		
		PropertyListing_To_AR_Listing,
		PropertyListing_To_Property,
		#endregion
		
		#region PropertyOrder		
		PropertyOrder_To_Order,
		PropertyOrder_To_Property,
		#endregion
		
		#region PropertySBOrder		
		PropertySBOrder_To_Property,
		PropertySBOrder_To_SB_Order,
		#endregion
		
		#region QuoteDetail		
		QuoteDetail_To_Quote,
		QuoteDetail_To_Product,
		#endregion
		
		#region Quote		
		Quote_To_QuoteDetails,
		#endregion
		
		#region Region		
		Region_To_SubRegions,
		Region_To_State1,
		#endregion
		
		#region RIPLocation		
		RIPLocation_To_AJPS_Rules,
		RIPLocation_To_AJPS_Rules1,
		RIPLocation_To_AJPS_Rules2,
		RIPLocation_To_AJPS_Rules3,
		RIPLocation_To_AJPS_Rules4,
		RIPLocation_To_AJPS_Rules5,
		#endregion
		
		#region RunSheet		
		RunSheet_To_RunsheetDetailsNotes,
		RunSheet_To_RunsheetDetailsSBs,
		RunSheet_To_RunSheetDetails,
		RunSheet_To_Manager,
		RunSheet_To_Truck,
		RunSheet_To_Truck1,
		#endregion
		
		#region RunsheetDetailsNote		
		RunsheetDetailsNote_To_RunSheet,
		#endregion
		
		#region RunsheetDetailsSB		
		RunsheetDetailsSB_To_RunSheet,
		RunsheetDetailsSB_To_SB_Order,
		#endregion
		
		#region SB_Inventory		
		SB_Inventory_To_Manager,
		SB_Inventory_To_Client,
		SB_Inventory_To_Product,
		#endregion
		
		#region SB_OrderDetail		
		SB_OrderDetail_To_Product,
		SB_OrderDetail_To_SB_Order,
		#endregion
		
		#region SMS_Provider		
		SMS_Provider_To_SMS_Queues,
		SMS_Provider_To_SMS_ReplyLogs,
		#endregion
		
		#region SMS_Queue		
		SMS_Queue_To_SMS_ReplyLogs,
		SMS_Queue_To_SMS_Provider,
		SMS_Queue_To_OrderOtherDetail,
		#endregion
		
		#region SMS_ReplyLog		
		SMS_ReplyLog_To_SMS_Provider,
		SMS_ReplyLog_To_SMS_Queue,
		#endregion
		
		#region SMS_Subscription		
		SMS_Subscription_To_Client,
		#endregion
		
		#region State		
		State_To_BusinessRegions,
		State_To_Customers,
		State_To_Locations,
		State_To_Managers,
		State_To_Photographers,
		State_To_Regions,
		State_To_Clients,
		State_To_ClientNationalDeliveryLocations,
		State_To_DroneLocations,
		State_To_Accounts,
		#endregion
		
		#region SubRegion		
		SubRegion_To_LocationsDatas,
		SubRegion_To_Region,
		#endregion
		
		#region TempOrderDetail		
		TempOrderDetail_To_TempOrder,
		#endregion
		
		#region TempOrder		
		TempOrder_To_TempOrderDetails,
		#endregion
		
		#region Truck		
		Truck_To_RunSheets,
		Truck_To_RunSheets1,
		Truck_To_DriverRegions,
		Truck_To_DespatchDetails,
		Truck_To_DespatchDetails1,
		Truck_To_SB_Orders,
		Truck_To_SB_Orders1,
		Truck_To_Manager,
		#endregion
		
		#region WebSiteAreaImageStore		
		WebSiteAreaImageStore_To_WebSitePropertyArea,
		#endregion
		
		#region WebSitePropertyArea		
		WebSitePropertyArea_To_WebSiteAreaImageStores,
		WebSitePropertyArea_To_AR_Listing,
		#endregion
		
		#region WebSiteSingleProperty		
		WebSiteSingleProperty_To_AR_Listing,
		WebSiteSingleProperty_To_WebSiteTemplate,
		#endregion
		
		#region WebSiteTemplate		
		WebSiteTemplate_To_WebSiteSingleProperties,
		#endregion
		
		#region WorkflowAlert		
		WorkflowAlert_To_ODPackageContent,
		WorkflowAlert_To_OrderDetail,
		WorkflowAlert_To_Order,
		WorkflowAlert_To_WorkflowAlertType,
		WorkflowAlert_To_WorkflowState,
		#endregion
		
		#region WorkflowAlertType		
		WorkflowAlertType_To_WorkflowAlerts,
		#endregion
		
		#region WorkflowHistory		
		WorkflowHistory_To_ODPackageContent,
		WorkflowHistory_To_OrderDetail,
		WorkflowHistory_To_Order,
		WorkflowHistory_To_WorkflowState,
		#endregion
		
		#region WorkflowState		
		WorkflowState_To_WorkflowAlerts,
		WorkflowState_To_WorkflowHistories,
		#endregion
		
		#region AOP_Template		
		AOP_Template_To_AOP_AnalyzeQueues,
		AOP_Template_To_AOP_TemplateProducts,
		AOP_Template_To_ClientGroup,
		AOP_Template_To_Client,
		#endregion
		
		#region AOP_QueueStatus		
		AOP_QueueStatus_To_AOP_AnalyzeQueues,
		AOP_QueueStatus_To_AOP_JobQueues,
		AOP_QueueStatus_To_Design_JobQueues,
		#endregion
		
		#region ClientFranchise		
		ClientFranchise_To_ClientFranchiseRelations,
		ClientFranchise_To_UserLogons,
		#endregion
		
		#region ClientFranchiseRelation		
		ClientFranchiseRelation_To_ClientFranchise,
		ClientFranchiseRelation_To_Client,
		#endregion
		
		#region ClientContact		
		ClientContact_To_UserLogons,
		ClientContact_To_ClientFavs,
		ClientContact_To_SB_Orders,
		ClientContact_To_Client,
		#endregion
		
		#region UserLogon		
		UserLogon_To_ClientContact,
		UserLogon_To_ClientFranchise,
		UserLogon_To_ClientGroup,
		UserLogon_To_Client,
		#endregion
		
		#region AR_PropertyType		
		AR_PropertyType_To_AR_Properties,
		#endregion
		
		#region Client		
		Client_To_ABCFP_InboundQueues,
		Client_To_ABCFP_IncomingFeedsMappings,
		Client_To_ABCFP_OutgoingAgentsInfos,
		Client_To_AR_Agreements,
		Client_To_AR_BlockedClient,
		Client_To_AR_Listings,
		Client_To_AR_PluginClient,
		Client_To_AR_PluginGroupClients,
		Client_To_ClientsDisplayInfo,
		Client_To_ClientsForAllManager,
		Client_To_ClientsLocations,
		Client_To_ClientsOOProfile,
		Client_To_ClientsPrefs,
		Client_To_CRM_MappedClients,
		Client_To_FloorplanPackages,
		Client_To_Hosting_HostingConfigurations,
		Client_To_Orders,
		Client_To_SB_Inventories,
		Client_To_SMS_Subscriptions,
		Client_To_AOP_Templates,
		Client_To_ClientFranchiseRelations,
		Client_To_ClientContacts,
		Client_To_UserLogons,
		Client_To_ClientFavs,
		Client_To_ABCVIS_ClientsAssetRentals,
		Client_To_TemplateDetails,
		Client_To_RegionalPropertyRequests,
		Client_To_Properties,
		Client_To_SB_Orders,
		Client_To_BusinessRegion,
		Client_To_ClientGroup,
		Client_To_Manager,
		Client_To_PrintTemplate,
		Client_To_State1,
		Client_To_PriceList,
		Client_To_Account,
		#endregion
		
		#region PriceListDetail		
		PriceListDetail_To_PrintTemplate,
		PriceListDetail_To_Product,
		PriceListDetail_To_PriceList,
		#endregion
		
		#region ProductRule		
		ProductRule_To_Product,
		#endregion
		
		#region OnlineOrderCategory		
		OnlineOrderCategory_To_OnlineOrderCategoryRules,
		OnlineOrderCategory_To_OnlineOrderSubCategories,
		OnlineOrderCategory_To_Products,
		OnlineOrderCategory_To_PrintReadyTemplates,
		#endregion
		
		#region OnlineOrderCategoryRule		
		OnlineOrderCategoryRule_To_OnlineOrderCategory,
		#endregion
		
		#region OnlineOrderSubCategory		
		OnlineOrderSubCategory_To_OnlineOrderCategory,
		#endregion
		
		#region PackageContentGroup		
		PackageContentGroup_To_PackageContentGroupProducts,
		PackageContentGroup_To_Product,
		#endregion
		
		#region PackageContentGroupProduct		
		PackageContentGroupProduct_To_PackageContentGroup,
		#endregion
		
		#region ProductGroupDescription		
		ProductGroupDescription_To_Products,
		#endregion
		
		#region Product		
		Product_To_OrderDetails,
		Product_To_Package,
		Product_To_ProductManagerExclusives,
		Product_To_ProductPricings,
		Product_To_QuoteDetails,
		Product_To_SB_Inventories,
		Product_To_SB_OrderDetails,
		Product_To_PriceListDetails,
		Product_To_ProductRules,
		Product_To_PackageContentGroups,
		Product_To_ClientFavs,
		Product_To_FloorPlanOrders,
		Product_To_Design_Documents,
		Product_To_OnlineOrderCategory,
		Product_To_ProductGroupDescription,
		Product_To_ProductSizeCode,
		Product_To_ProductType,
		Product_To_WorkflowType,
		Product_To_AJPS_Rule,
		#endregion
		
		#region AOP_JobQueue		
		AOP_JobQueue_To_AOP_QueueStatus,
		AOP_JobQueue_To_AOP_JobDocument,
		#endregion
		
		#region AJPS_Rule		
		AJPS_Rule_To_ODPackageContents,
		AJPS_Rule_To_OrderDetails,
		AJPS_Rule_To_PackageContents,
		AJPS_Rule_To_Products,
		AJPS_Rule_To_RIPLocation,
		AJPS_Rule_To_RIPLocation7,
		AJPS_Rule_To_RIPLocation8,
		AJPS_Rule_To_RIPLocation9,
		AJPS_Rule_To_RIPLocation10,
		AJPS_Rule_To_RIPLocation11,
		#endregion
		
		#region PriceList		
		PriceList_To_Clients,
		PriceList_To_PriceListDetails,
		#endregion
		
		#region DriverRegions		
		DriverRegions_To_Locations,
		DriverRegions_To_Truck,
		#endregion
		
		#region ClientFav		
		ClientFav_To_ClientContact,
		ClientFav_To_Client,
		ClientFav_To_Product,
		#endregion
		
		#region AOP_JobDocument		
		AOP_JobDocument_To_AOP_JobQueues,
		AOP_JobDocument_To_AOP_TemplateProduct,
		AOP_JobDocument_To_OrderDetail,
		AOP_JobDocument_To_AOP_DocumentStatus,
		AOP_JobDocument_To_Order,
		#endregion
		
		#region ABCVIS_Asset		
		ABCVIS_Asset_To_ABCVIS_ClientsAssetRentals,
		ABCVIS_Asset_To_ABCVIS_AssetType,
		#endregion
		
		#region ABCVIS_Template		
		ABCVIS_Template_To_ABCVIS_ClientsAssetRentals,
		#endregion
		
		#region ABCVIS_AssetType		
		ABCVIS_AssetType_To_ABCVIS_Assets,
		#endregion
		
		#region ABCVIS_Listing		
		ABCVIS_Listing_To_AR_Listing,
		ABCVIS_Listing_To_ABCVIS_ClientsAssetRental,
		#endregion
		
		#region ABCVIS_ListingDisplayOption		
		ABCVIS_ListingDisplayOption_To_ABCVIS_ClientsAssetRentals,
		#endregion
		
		#region AR_Property		
		AR_Property_To_AR_Image,
		AR_Property_To_AR_Listing,
		AR_Property_To_AR_PropertyType,
		#endregion
		
		#region ABCVIS_ClientsAssetRental		
		ABCVIS_ClientsAssetRental_To_ABCVIS_Listings,
		ABCVIS_ClientsAssetRental_To_ABCVIS_Asset,
		ABCVIS_ClientsAssetRental_To_ABCVIS_ListingDisplayOption,
		ABCVIS_ClientsAssetRental_To_ABCVIS_Template,
		ABCVIS_ClientsAssetRental_To_Client,
		#endregion
		
		#region PDF_Template		
		PDF_Template_To_ProductSizeCode,
		#endregion
		
		#region ClientNationalDeliveryLocation		
		ClientNationalDeliveryLocation_To_State1,
		#endregion
		
		#region DroneLocation		
		DroneLocation_To_State1,
		#endregion
		
		#region DroneAuthorisation		
		DroneAuthorisation_To_Photographer,
		DroneAuthorisation_To_Photographer1,
		DroneAuthorisation_To_Order,
		DroneAuthorisation_To_Photographer2,
		#endregion
		
		#region TemplateChangeRequest		
		TemplateChangeRequest_To_Artist,
		TemplateChangeRequest_To_Order,
		#endregion
		
		#region PrintReadyTemplate		
		PrintReadyTemplate_To_OnlineOrderCategory,
		PrintReadyTemplate_To_ProductSizeCode,
		#endregion
		
		#region FloorPlanOrder		
		FloorPlanOrder_To_Order,
		FloorPlanOrder_To_Product,
		#endregion
		
		#region RunSheetDetail		
		RunSheetDetail_To_RunSheet,
		RunSheetDetail_To_DespatchDetail,
		#endregion
		
		#region DespatchOtherDetail		
		DespatchOtherDetail_To_Consignment,
		DespatchOtherDetail_To_Order,
		#endregion
		
		#region OrderOtherInfo		
		OrderOtherInfo_To_Order,
		#endregion
		
		#region TemplateDetail		
		TemplateDetail_To_Artist,
		TemplateDetail_To_ClientGroup,
		TemplateDetail_To_Client,
		#endregion
		
		#region PhotoOrderDetail		
		PhotoOrderDetail_To_Order,
		#endregion
		
		#region DespatchDetail		
		DespatchDetail_To_RunSheetDetails,
		DespatchDetail_To_Consignment,
		DespatchDetail_To_Order,
		DespatchDetail_To_Truck,
		DespatchDetail_To_Truck1,
		#endregion
		
		#region RegionalPropertyRequest		
		RegionalPropertyRequest_To_Client,
		#endregion
		
		#region Design_JobQueue		
		Design_JobQueue_To_AOP_QueueStatus,
		Design_JobQueue_To_Design_Document,
		#endregion
		
		#region BoardApproval		
		BoardApproval_To_Order,
		#endregion
		
		#region PhotoOrder		
		PhotoOrder_To_Order,
		PhotoOrder_To_Photographer,
		#endregion
		
		#region TemplateRequest		
		TemplateRequest_To_Artist,
		TemplateRequest_To_Property,
		#endregion
		
		#region Account		
		Account_To_AccountCredits,
		Account_To_Orders,
		Account_To_Payments,
		Account_To_Clients,
		Account_To_State1,
		#endregion
		
		#region Property		
		Property_To_PropertyListing,
		Property_To_PropertyOrders,
		Property_To_PropertySBOrders,
		Property_To_TemplateRequests,
		Property_To_Design_Documents,
		Property_To_Client,
		Property_To_Location,
		#endregion
		
		#region Design_Document		
		Design_Document_To_Design_JobQueues,
		Design_Document_To_AOP_TemplateProduct,
		Design_Document_To_Order,
		Design_Document_To_Product,
		Design_Document_To_Property,
		#endregion
		
		#region SB_Order		
		SB_Order_To_PropertySBOrder,
		SB_Order_To_RunsheetDetailsSBs,
		SB_Order_To_SB_OrderDetails,
		SB_Order_To_ClientContact,
		SB_Order_To_Client,
		SB_Order_To_Manager,
		SB_Order_To_Truck,
		SB_Order_To_Truck1,
		#endregion
		
		#region OrderOtherDetail		
		OrderOtherDetail_To_SMS_Queues,
		OrderOtherDetail_To_Location,
		OrderOtherDetail_To_Order,
		#endregion
		
		
	}
}
#pragma warning restore 1591
