 
#pragma warning disable 1591
//-------------------------------------------------------------------------------------
// <auto-generated>
//		This code was generated by WcfProxy proxy generation template for C#
//		Generated at 07/17/2026 09:51:50
//	
//	Service interface: 
//						Abc.OnlineBL.Service.IAccountService
//						Abc.OnlineBL.Service.IAOPService
//						Abc.OnlineBL.Service.IClientService
//						Abc.OnlineBL.Service.IDesignService
//						Abc.OnlineBL.Service.IFloorPlanService
//						Abc.OnlineBL.Service.IManagerService
//						Abc.OnlineBL.Service.IOrderService
//						Abc.OnlineBL.Service.IPhotoSysRunSheetService
//						Abc.OnlineBL.Service.IProductService
//						Abc.OnlineBL.Service.ITemplateManagerService
//						Abc.OnlineBL.Service.IWorkflowService
//
//		Changes to this file may cause incorrect behavior and will be lost if the
//		code is regenerated.
//	</auto-generated>
//-------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.IO;
using System.Linq;
using System.Reflection;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Description;
using System.Text;
using System.Threading;

namespace Abc.OnlineBL.ServiceProxy
{	
	#region ExceptionHandlingProxyBase Class
	/// <summary>
	/// ExceptionHandlingProxyBase
	/// </summary>
	/// <Remarks>
	/// This code was generated by the Exception Handling WCF Proxy Generator add-in for Visual Studio 2008
	/// For updates and to view the supporting webcast go to http://wcfproxygenerator.codeplex.com
	/// Also go to http://wcfguidanceforwpf.codeplex.com for related whitepapers, webcasts and code samples	
	/// </Remarks>
	/// <typeparam name="T"></typeparam>
	public abstract class ExceptionHandlingProxyBase<T> : ICommunicationObject, IDisposable
			where T : class
	{
		// state
		private bool IsOpened { get; set; }
		/// <summary>
		/// Gets or sets a value indicating whether this instance is disposed.
		/// </summary>
		/// <value>
		/// 	<c>true</c> if this instance is disposed; otherwise, <c>false</c>.
		/// </value>
		public bool IsDisposed { get; private set; }

		// lock
		private object m_channelLock = new object();
		private bool m_isInitialized = false;
		private bool m_isProxyCreated = false;
		private ManualResetEvent m_proxyRecreationLock = new ManualResetEvent(true);
		/// <summary>
		/// Lock wait
		/// </summary>
		protected int m_proxyRecreationLockWait = 1000;

		// channel
		private ChannelFactory<T> m_channelFactory = null;
		private T m_channel = default(T);

		#region Constructors

		/// <summary>
		/// Initializes a new instance of the <see cref="ExceptionHandlingProxyBase&lt;T&gt;"/> class.
		/// </summary>
		public ExceptionHandlingProxyBase()
		{
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ExceptionHandlingProxyBase&lt;T&gt;"/> class.
		/// </summary>
		/// <param name="endpointConfigurationName">Name of the endpoint configuration.</param>
		public ExceptionHandlingProxyBase(string endpointConfigurationName)
		{
			Initialize(endpointConfigurationName);
		}

		/// <summary>
		/// Initializes the specified endpoint configuration name.
		/// </summary>
		/// <param name="endpointConfigurationName">Name of the endpoint configuration.</param>
		protected virtual void Initialize(string endpointConfigurationName)
		{
			if (this.m_isInitialized) throw new InvalidOperationException("Object already initialized.");
			this.m_isInitialized = true;

			m_channelFactory = new ChannelFactory<T>(endpointConfigurationName);
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ExceptionHandlingProxyBase&lt;T&gt;"/> class.
		/// </summary>
		/// <param name="endpointConfigurationName">Name of the endpoint configuration.</param>
		/// <param name="remoteAddress">The remote address.</param>
		public ExceptionHandlingProxyBase(string endpointConfigurationName, string remoteAddress)
		{
			Initialize(endpointConfigurationName, remoteAddress);
		}

		/// <summary>
		/// Initializes the specified endpoint configuration name.
		/// </summary>
		/// <param name="endpointConfigurationName">Name of the endpoint configuration.</param>
		/// <param name="remoteAddress">The remote address.</param>
		protected virtual void Initialize(string endpointConfigurationName, string remoteAddress)
		{
			if (this.m_isInitialized) throw new InvalidOperationException("Object already initialized.");
			this.m_isInitialized = true;

			m_channelFactory = new ChannelFactory<T>(endpointConfigurationName, new EndpointAddress(remoteAddress));
		}

		/// <summary>
		/// Initializes a new instance of the <see cref="ExceptionHandlingProxyBase&lt;T&gt;"/> class.
		/// </summary>
		/// <param name="binding">The binding.</param>
		/// <param name="remoteAddress">The remote address.</param>
		public ExceptionHandlingProxyBase(Binding binding, EndpointAddress remoteAddress)
		{
			Initialize(binding, remoteAddress);
		}

		/// <summary>
		/// Initializes the specified binding.
		/// </summary>
		/// <param name="binding">The binding.</param>
		/// <param name="remoteAddress">The remote address.</param>
		protected virtual void Initialize(Binding binding, EndpointAddress remoteAddress)
		{
			if (this.m_isInitialized) throw new InvalidOperationException("Object already initialized.");
			this.m_isInitialized = true;

			m_channelFactory = new ChannelFactory<T>(binding, remoteAddress);
		}

		#endregion

		#region Proxy creation

		/// <summary>
		/// Event occurs after proxy is recreated.
		/// </summary>
		public event EventHandler AfterRecreateProxy;

		/// <summary>
		/// Creates the proxy.
		/// </summary>
		protected virtual void CreateProxy()
		{

			lock (this.m_channelLock)
			{
				if (this.m_isProxyCreated) throw new InvalidOperationException("Proxy already created.");
				CreateInnerChannel();
				this.m_isProxyCreated = true;

			}
		}

		/// <summary>
		/// Recreates the proxy.
		/// </summary>
		protected virtual void RecreateProxy()
		{
			lock (this.m_channelLock)
			{
				//TODO: Remove this from TT when u don't need it for logging
				Logger.Warn("Recreating Proxy Type {0}", this.GetType().FullName);
				
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");

				CreateInnerChannel();

				if (AfterRecreateProxy != null)
					AfterRecreateProxy(this, null);
			}
		}

		private void CreateInnerChannel()
		{
			lock (this.m_channelLock)
			{
				if (m_channelFactory == null)
					throw new InvalidOperationException("Proxy invalid. This occurs when you use the default constructor.");

				m_channel = m_channelFactory.CreateChannel();

				ICommunicationObject co = m_channel as ICommunicationObject;
				co.Faulted += InnerChannel_Faulted;
				co.Closed += InnerChannel_Closed;
				co.Closing += InnerChannel_Closing;
				co.Opened += InnerChannel_Opened;
				co.Opening += InnerChannel_Opening;
			}
		}
		#endregion

		#region Communication events

		private void InnerChannel_Opening(object sender, EventArgs e)
		{
			lock (m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");

				if (this.Opening != null)
					this.Opening(sender, e);
			}
		}

		private void InnerChannel_Opened(object sender, EventArgs e)
		{
			lock (m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");

				if (this.Opened != null)
					this.Opened(sender, e);
			}
		}


		void InnerChannel_Closing(object sender, EventArgs e)
		{
			lock (m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");

				if (this.Closing != null)
					this.Closing(sender, e);
			}
		}
		private void InnerChannel_Closed(object sender, EventArgs e)
		{
			lock (m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");

				try
				{
					this.m_proxyRecreationLock.Reset(); // will stop other threads from trying to Invoke() while recreating the proxy

					if (this.Closed != null)
						this.Closed(sender, e);

					OnClosed();
				}
				finally
				{
					this.m_proxyRecreationLock.Set(); // will stop other threads from trying to Invoke() while recreating the proxy
				}

			}

		}

		/// <summary>
		/// Called when [closed].
		/// </summary>
		protected virtual void OnClosed()
		{
			lock (this.m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");

				this.Abort();
				RecreateProxy();

			}
		}

		private void InnerChannel_Faulted(object sender, EventArgs e)
		{
			lock (m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");

				try
				{
					this.m_proxyRecreationLock.Reset(); // will stop other threads from trying to Invoke() while recreating the proxy

					if (this.Faulted != null)
						this.Faulted(sender, e);

					OnFaulted();
				}
				finally
				{
					this.m_proxyRecreationLock.Set(); // will stop other threads from trying to Invoke() while recreating the proxy
				}
			}

		}

		/// <summary>
		/// Called when [faulted].
		/// </summary>
		protected virtual void OnFaulted()
		{
			lock (this.m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");

				this.Abort();
				RecreateProxy();
			}
		}

		#endregion

		# region Channel Properties
		/// <summary>
		/// Gets the inner channel.
		/// </summary>
		/// <value>The inner channel.</value>
		public IClientChannel InnerChannel
		{
			get
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");

				return (IClientChannel)m_channel;
			}
		}

		/// <summary>
		/// Gets the client credentials.
		/// </summary>
		/// <value>The client credentials.</value>
		public ClientCredentials ClientCredentials
		{
			get
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");

				return m_channelFactory.Credentials;
			}
		}

		/// <summary>
		/// Gets the endpoint.
		/// </summary>
		/// <value>The endpoint.</value>
		public ServiceEndpoint Endpoint
		{
			get
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");

				return m_channelFactory.Endpoint;
			}
		}

		/// <summary>
		/// Gets the current state of the communication-oriented object.
		/// </summary>
		/// <value></value>
		/// <returns>The value of the <see cref="T:System.ServiceModel.CommunicationState"/> of the object.</returns>
		public CommunicationState State
		{
			get
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");

				IChannel channel = (IChannel)m_channel;
				if (channel == null)
					return CommunicationState.Created;

				return channel.State;
			}
		}

		#endregion

		#region ICommunicationObject Members

		/// <summary>
		/// Occurs when the communication object completes its transition from the closing state into the closed state.
		/// </summary>
		public event EventHandler Closed;
		/// <summary>
		/// Occurs when the communication object first enters the closing state.
		/// </summary>
		public event EventHandler Closing;
		/// <summary>
		/// Occurs when the communication object first enters the faulted state.
		/// </summary>
		public event EventHandler Faulted;
		/// <summary>
		/// Occurs when the communication object completes its transition from the opening state into the opened state.
		/// </summary>
		public event EventHandler Opened;
		/// <summary>
		/// Occurs when the communication object first enters the opening state.
		/// </summary>
		public event EventHandler Opening;

		/// <summary>
		/// Causes a communication object to transition immediately from its current state into the closed state.
		/// </summary>
		public void Abort()
		{
			lock (this.m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");

				ICommunicationObject co = (ICommunicationObject)m_channel;
				co.Closed -= new EventHandler(this.InnerChannel_Closed);
				co.Closing -= new EventHandler(this.InnerChannel_Closing);
				co.Faulted -= new EventHandler(this.InnerChannel_Faulted);
				co.Opened -= new EventHandler(this.InnerChannel_Opened);
				co.Opening -= new EventHandler(this.InnerChannel_Opening);
				co.Abort();
			}
		}

		/// <summary>
		/// Causes a communication object to transition from the created state into the opened state within a specified interval of time.
		/// </summary>
		/// <param name="timeout">The <see cref="T:System.Timespan"/> that specifies how long the send operation has to complete before timing out.</param>
		/// <exception cref="T:System.ServiceModel.CommunicationException">The <see cref="T:System.ServiceModel.ICommunicationObject"/> was unable to be opened and has entered the <see cref="F:System.ServiceModel.CommunicationState.Faulted"/> state.</exception>
		/// <exception cref="T:System.TimeoutException">The specified timeout elapsed before the <see cref="T:System.ServiceModel.ICommunicationObject"/> was able to enter the <see cref="F:System.ServiceModel.CommunicationState.Opened"/> state and has entered the <see cref="F:System.ServiceModel.CommunicationState.Faulted"/> state.</exception>
		public void Open(TimeSpan timeout)
		{
			lock (this.m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");

				if (!this.IsOpened)
				{
					EnsureProxy();
					((ICommunicationObject)m_channel).Open(timeout);
					this.IsOpened = true;
				}
			}
		}

		/// <summary>
		/// Causes a communication object to transition from the created state into the opened state.
		/// </summary>
		/// <exception cref="T:System.ServiceModel.CommunicationException">The <see cref="T:System.ServiceModel.ICommunicationObject"/> was unable to be opened and has entered the <see cref="F:System.ServiceModel.CommunicationState.Faulted"/> state.</exception>
		/// <exception cref="T:System.TimeoutException">The default open timeout elapsed before the <see cref="T:System.ServiceModel.ICommunicationObject"/> was able to enter the <see cref="F:System.ServiceModel.CommunicationState.Opened"/> state and has entered the <see cref="F:System.ServiceModel.CommunicationState.Faulted"/> state.</exception>
		public void Open()
		{
			lock (this.m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");

				if (!this.IsOpened)
				{
					EnsureProxy();
					((ICommunicationObject)m_channel).Open();
					this.IsOpened = true;
				}
			}
		}

		/// <summary>
		/// Causes a communication object to transition from its current state into the closed state.
		/// </summary>
		/// <param name="timeout">The <see cref="T:System.Timespan"/> that specifies how long the send operation has to complete before timing out.</param>
		/// <exception cref="T:System.ServiceModel.CommunicationObjectFaultedException">
		/// 	<see cref="M:System.ServiceModel.ICommunicationObject.Close"/> was called on an object in the <see cref="F:System.ServiceModel.CommunicationState.Faulted"/> state.</exception>
		/// <exception cref="T:System.TimeoutException">The timeout elapsed before the <see cref="T:System.ServiceModel.ICommunicationObject"/> was able to close gracefully.</exception>
		public void Close(TimeSpan timeout)
		{
			lock (this.m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");
				((ICommunicationObject)m_channel).Close(timeout);
			}
		}

		/// <summary>
		/// Causes a communication object to transition from its current state into the closed state.
		/// </summary>
		/// <exception cref="T:System.ServiceModel.CommunicationObjectFaultedException">
		/// 	<see cref="M:System.ServiceModel.ICommunicationObject.Close"/> was called on an object in the <see cref="F:System.ServiceModel.CommunicationState.Faulted"/> state.</exception>
		/// <exception cref="T:System.TimeoutException">The default close timeout elapsed before the <see cref="T:System.ServiceModel.ICommunicationObject"/> was able to close gracefully.</exception>
		public void Close()
		{
			lock (this.m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");
				((ICommunicationObject)m_channel).Close();
			}
		}

		/// <summary>
		/// Begins an asynchronous operation to close a communication object with a specified timeout.
		/// </summary>
		/// <param name="timeout">The <see cref="T:System.Timespan"/> that specifies how long the send operation has to complete before timing out.</param>
		/// <param name="callback">The <see cref="T:System.AsyncCallback"/> delegate that receives notification of the completion of the asynchronous close operation.</param>
		/// <param name="state">An object, specified by the application, that contains state information associated with the asynchronous close operation.</param>
		/// <returns>
		/// The <see cref="T:System.IAsyncResult"/> that references the asynchronous close operation.
		/// </returns>
		/// <exception cref="T:System.ServiceModel.CommunicationObjectFaultedException">
		/// 	<see cref="M:System.ServiceModel.ICommunicationObject.BeginClose"/> was called on an object in the <see cref="F:System.ServiceModel.CommunicationState.Faulted"/> state.</exception>
		/// <exception cref="T:System.TimeoutException">The specified timeout elapsed before the <see cref="T:System.ServiceModel.ICommunicationObject"/> was able to close gracefully.</exception>
		public IAsyncResult BeginClose(TimeSpan timeout, AsyncCallback callback, object state)
		{
			lock (this.m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");
				return ((ICommunicationObject)m_channel).BeginClose(timeout, callback, state);
			}
		}

		/// <summary>
		/// Begins an asynchronous operation to close a communication object.
		/// </summary>
		/// <param name="callback">The <see cref="T:System.AsyncCallback"/> delegate that receives notification of the completion of the asynchronous close operation.</param>
		/// <param name="state">An object, specified by the application, that contains state information associated with the asynchronous close operation.</param>
		/// <returns>
		/// The <see cref="T:System.IAsyncResult"/> that references the asynchronous close operation.
		/// </returns>
		/// <exception cref="T:System.ServiceModel.CommunicationObjectFaultedException">
		/// 	<see cref="M:System.ServiceModel.ICommunicationObject.BeginClose"/> was called on an object in the <see cref="F:System.ServiceModel.CommunicationState.Faulted"/> state.</exception>
		/// <exception cref="T:System.TimeoutException">The default timeout elapsed before the <see cref="T:System.ServiceModel.ICommunicationObject"/> was able to close gracefully.</exception>
		public IAsyncResult BeginClose(AsyncCallback callback, object state)
		{
			lock (this.m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");
				return ((ICommunicationObject)m_channel).BeginClose(callback, state);
			}
		}

		/// <summary>
		/// Begins an asynchronous operation to open a communication object within a specified interval of time.
		/// </summary>
		/// <param name="timeout">The <see cref="T:System.Timespan"/> that specifies how long the send operation has to complete before timing out.</param>
		/// <param name="callback">The <see cref="T:System.AsyncCallback"/> delegate that receives notification of the completion of the asynchronous open operation.</param>
		/// <param name="state">An object, specified by the application, that contains state information associated with the asynchronous open operation.</param>
		/// <returns>
		/// The <see cref="T:System.IAsyncResult"/> that references the asynchronous open operation.
		/// </returns>
		/// <exception cref="T:System.ServiceModel.CommunicationException">The <see cref="T:System.ServiceModel.ICommunicationObject"/> was unable to be opened and has entered the <see cref="F:System.ServiceModel.CommunicationState.Faulted"/> state.</exception>
		/// <exception cref="T:System.TimeoutException">The specified timeout elapsed before the <see cref="T:System.ServiceModel.ICommunicationObject"/> was able to enter the <see cref="F:System.ServiceModel.CommunicationState.Opened"/> state and has entered the <see cref="F:System.ServiceModel.CommunicationState.Faulted"/> state.</exception>
		public IAsyncResult BeginOpen(TimeSpan timeout, AsyncCallback callback, object state)
		{
			lock (this.m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");
				return ((ICommunicationObject)m_channel).BeginClose(timeout, callback, state);
			}
		}

		/// <summary>
		/// Begins an asynchronous operation to open a communication object.
		/// </summary>
		/// <param name="callback">The <see cref="T:System.AsyncCallback"/> delegate that receives notification of the completion of the asynchronous open operation.</param>
		/// <param name="state">An object, specified by the application, that contains state information associated with the asynchronous open operation.</param>
		/// <returns>
		/// The <see cref="T:System.IAsyncResult"/> that references the asynchronous open operation.
		/// </returns>
		/// <exception cref="T:System.ServiceModel.CommunicationException">The <see cref="T:System.ServiceModel.ICommunicationObject"/> was unable to be opened and has entered the <see cref="F:System.ServiceModel.CommunicationState.Faulted"/> state.</exception>
		/// <exception cref="T:System.TimeoutException">The default open timeout elapsed before the <see cref="T:System.ServiceModel.ICommunicationObject"/> was able to enter the <see cref="F:System.ServiceModel.CommunicationState.Opened"/> state and has entered the <see cref="F:System.ServiceModel.CommunicationState.Faulted"/> state.</exception>
		public IAsyncResult BeginOpen(AsyncCallback callback, object state)
		{
			lock (this.m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");
				return ((ICommunicationObject)m_channel).BeginOpen(callback, state);
			}
		}

		/// <summary>
		/// Completes an asynchronous operation to close a communication object.
		/// </summary>
		/// <param name="result">The <see cref="T:System.IAsyncResult"/> that is returned by a call to the <see cref="M:System.ServiceModel.ICommunicationObject.BeginClose"/> method.</param>
		/// <exception cref="T:System.ServiceModel.CommunicationObjectFaultedException">
		/// 	<see cref="M:System.ServiceModel.ICommunicationObject.BeginClose"/> was called on an object in the <see cref="F:System.ServiceModel.CommunicationState.Faulted"/> state.</exception>
		/// <exception cref="T:System.TimeoutException">The timeout elapsed before the <see cref="T:System.ServiceModel.ICommunicationObject"/> was able to close gracefully.</exception>
		public void EndClose(IAsyncResult result)
		{
			lock (this.m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");
				((ICommunicationObject)m_channel).EndClose(result);
			}
		}

		/// <summary>
		/// Completes an asynchronous operation to open a communication object.
		/// </summary>
		/// <param name="result">The <see cref="T:System.IAsyncResult"/> that is returned by a call to the <see cref="M:System.ServiceModel.ICommunicationObject.BeginOpen"/> method.</param>
		/// <exception cref="T:System.ServiceModel.CommunicationException">The <see cref="T:System.ServiceModel.ICommunicationObject"/> was unable to be opened and has entered the <see cref="F:System.ServiceModel.CommunicationState.Faulted"/> state.</exception>
		/// <exception cref="T:System.TimeoutException">The timeout elapsed before the <see cref="T:System.ServiceModel.ICommunicationObject"/> was able to enter the <see cref="F:System.ServiceModel.CommunicationState.Opened"/> state and has entered the <see cref="F:System.ServiceModel.CommunicationState.Faulted"/> state.</exception>
		public void EndOpen(IAsyncResult result)
		{
			lock (this.m_channelLock)
			{
				if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");
				((ICommunicationObject)m_channel).EndOpen(result);
			}
		}


		#endregion

		#region IDisposable Members

		/// <summary>
		/// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
		/// </summary>
		public void Dispose()
		{
			lock (m_channelLock)
			{
				Cleanup();
				this.IsDisposed = true;
			}
		}

		/// <summary>
		/// Cleanups this instance.
		/// </summary>
		protected virtual void Cleanup()
		{
			try
			{
				ICommunicationObject co = (ICommunicationObject)m_channel;
				co.Closed -= InnerChannel_Closed;
				co.Closing -= InnerChannel_Closing;
				co.Faulted -= InnerChannel_Faulted;
				co.Opened -= InnerChannel_Opened;
				co.Opening -= InnerChannel_Opening;
				co.Close();
			}
			catch
			{
				try
				{
					ICommunicationObject co = (ICommunicationObject)m_channel;
					co.Abort();
				}
				catch { }
			}

			try
			{
				m_channelFactory.Close();
			}
			catch
			{
				try
				{
					m_channelFactory.Abort();
				}
				catch { }
			}

		}

		#endregion

		#region Invoke

		/// <summary>
		/// RetryInvokeHandler
		/// </summary>
		public delegate void RetryInvokeHandler(out Message unreadMessage);
		/// <summary>
		/// Occurs when [retry invoke].
		/// </summary>
		public event RetryInvokeHandler RetryInvoke;

		/// <summary>
		/// Invokes the specified operation name.
		/// </summary>
		/// <param name="operationName">Name of the operation.</param>
		/// <param name="parameters">The parameters.</param>
		protected void Invoke(string operationName, params object[] parameters)
		{
			if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");
			this.Open();

			MethodInfo methodInfo = GetMethod(operationName);

			try
			{
				// manual reset event here, turn it on when faulted
				// other threads will queue, and get a successful Invoke() once proxy is recreated
				this.m_proxyRecreationLock.WaitOne(this.m_proxyRecreationLockWait); // if this takes longer than 1 second we have bigger problems
				methodInfo.Invoke(m_channel, parameters);
			}
			catch (TargetInvocationException targetEx) // Invoke() always throws this type
			{
				CommunicationException commEx = targetEx.InnerException as CommunicationException;
				if (commEx == null)
				{
					throw targetEx.InnerException; // not a communication exception, throw it
				}

				FaultException faultEx = commEx as FaultException;
				if (faultEx != null)
				{
					throw targetEx.InnerException; // the service threw a fault, throw it
				}

				try
				{
					// manual reset event here, turn it on when faulted
					// other threads will queue, and get a successful Invoke() once proxy is recreated
					this.m_proxyRecreationLock.WaitOne(this.m_proxyRecreationLockWait); // if this takes longer than 1 second we have bigger problems

					// if it is a Message type it won't work, must fire RetryInvoke() and hopefully derived class will supply the original
					// message to send again...
					if (parameters.Length == 1 && parameters[0] is Message)
					{
						Message unreadMessage;
						RetryInvoke(out unreadMessage);
						methodInfo.Invoke(m_channel, new object[] { unreadMessage }); // a communication exception, retry once
					}
					else
						methodInfo.Invoke(m_channel, parameters); // a communication exception, retry once
				}
				catch (TargetInvocationException targetEx2)
				{
					RecreateProxy();
					throw targetEx2.InnerException; // still failed, throw it
				}
			}
		}

		/// <summary>
		/// Invokes the specified operation name.
		/// </summary>
		/// <typeparam name="TResult">The type of the result.</typeparam>
		/// <param name="operationName">Name of the operation.</param>
		/// <param name="parameters">The parameters.</param>
		/// <returns></returns>
		protected TResult Invoke<TResult>(string operationName, params object[] parameters)
		{
			MethodInfo methodInfo = GetMethod(operationName);
			return Invoke<TResult>(methodInfo, parameters);
		}

		/// <summary>
		/// Invokes the specified method info.
		/// </summary>
		/// <typeparam name="TResult">The type of the result.</typeparam>
		/// <param name="methodInfo">The method info.</param>
		/// <param name="parameters">The parameters.</param>
		/// <returns></returns>
		protected TResult Invoke<TResult>(MethodInfo methodInfo, params object[] parameters)
		{

			if (this.IsDisposed) throw new InvalidOperationException("Cannot use disposed object.");
			this.Open();

			TResult result = default(TResult);

			try
			{
				// manual reset event here, turn it on when faulted
				// other threads will queue, and get a successful Invoke() once proxy is recreated
				this.m_proxyRecreationLock.WaitOne(this.m_proxyRecreationLockWait); // if this takes longer than 1 second we have bigger problems
				result = (TResult)methodInfo.Invoke(m_channel, parameters);
			}
			catch (TargetInvocationException targetEx) // Invoke() always throws this type
			{
				CommunicationException commEx = targetEx.InnerException as CommunicationException;
				if (commEx == null)
				{
					throw targetEx.InnerException; // not a communication exception, throw it
				}

				FaultException faultEx = commEx as FaultException;
				if (faultEx != null)
				{
					throw targetEx.InnerException; // the service threw a fault, throw it
				}

				// a communication exception, retry once
				try
				{
					// manual reset event here, turn it on when faulted
					// other threads will queue, and get a successful Invoke() once proxy is recreated
					this.m_proxyRecreationLock.WaitOne(this.m_proxyRecreationLockWait); // if this takes longer than 1 second we have bigger problems

					// if it is a Message type it won't work, must fire RetryInvoke() and hopefully derived class will supply the original
					// message to send again...
					if (parameters.Length == 1 && parameters[0] is Message)
					{
						Message unreadMessage;
						RetryInvoke(out unreadMessage);
						result = (TResult)methodInfo.Invoke(m_channel, new object[] { unreadMessage }); // communication exception, retry once
					}
					else
						result = (TResult)methodInfo.Invoke(m_channel, parameters); // communication exception, retry once

				}
				catch (TargetInvocationException targetEx2)
				{
					Logger.Exception(targetEx2.InnerException,"ServiceProxy Error: " + targetEx2.InnerException.Message);
					RecreateProxy();
					throw targetEx2.InnerException; // still failed, throw it
				}
			}

			return result;
		}

		internal MethodInfo GetMethod(string operationName)
		{
			Type t = typeof(T);

			HashSet<MethodInfo> methods = new HashSet<MethodInfo>();
			GetMethodsRecursive(t, BindingFlags.Public | BindingFlags.Instance, ref methods);

			var result = from m in methods
									 where m.Name == operationName
									 select m;

			if (result.Count() == 0)
				throw new InvalidOperationException(String.Format("Unable to invoke method {0}. Method does not exist on contract {1}.", operationName, t.ToString()));

			if (result.Count() > 1)
				throw new InvalidOperationException(String.Format("Unable to invoke method {0}. More than one method is defined on contract {1} by the same name. Overloads not supported by CachedProxyBase.", operationName, t.ToString()));

			return result.First();
		}

		private void GetMethodsRecursive(Type t, BindingFlags flags, ref HashSet<MethodInfo> methods)
		{
			MethodInfo[] children = t.GetMethods(flags);
			methods.UnionWith(children);
			foreach (Type contract in t.GetInterfaces())
			{
				GetMethodsRecursive(contract, flags, ref methods);
			}
		}

		private void EnsureProxy()
		{
			lock (this.m_channelLock)
			{
				if (!this.m_isProxyCreated)
				{
					this.CreateProxy();
				}
			}
		}

		#endregion

	}
	#endregion
}
